### ISSUE TITLE
it duznt werk

### ISSUE THREAD

**Issue by drtshock** [mbax/PluginCatcher#4]
^

**Comment by turt2live** [comment]
cunfurmed

**Comment by natemort** [comment]
+1

**Comment by SuperSpyTX** [comment]
+9001

**Comment by mbax** [comment]
oh
fixing

**Comment by drtshock** [comment]
OMG YOU ROCK

**Comment by SuperSpyTX** [comment]
YES IT WORKS AGAIN THANKS MBAX

**Comment by natemort** [comment]
@mbax LATEST BUILD IS STILL BROKEN

**Comment by SuperSpyTX** [comment]
@evilmidget38 NOOOO WHY YOU LIER

**Comment by SuperSpyTX** [comment]
2 months and no fix.  y mbaxter.  y would u do dis.

**Comment by mbax** [comment]
oops

**Comment by drtshock** [comment]
stil not fix?

**Comment by SuperSpyTX** [comment]
idk @evilmidget38 said latest build broken.

i tried latest build but it crashes every tiem

**Comment by turt2live** [comment]
cunfirmd

i cnt get it 2 werk on my srver. 2 mny errs

**Comment by Iaccidentally** [comment]
BUT THEN WHO WAS PHONE???

**Comment by davismariotti** [comment]
Y U NO PUSH WRITE BUTTONS?!

**Comment by lol768** [comment]
omg such trribl support - y u no reply in **FIVE HOURS**!?!?!?!?!

# imma find a better pluguin than this

**Comment by turt2live** [comment]
hear is my err in my consoll

Java.MBAXFailedException (MainClassHere.java:88)
    at org.fail.mbaxter.everything.MainClass.java (MainClass.java:88)
    at org.fail.mbaxter.everything.AnotherClass.java (AnotherClass.java:88)
    at org.fail.mbaxter.everything.BukkitIsNotAtFault.java (BukkitIsNotAtFault.java:88)
    at org.fail.mbaxter.everything.Derp.java (Derp.java:88)
    at org.fail.mbaxter.everything.cats.everywhere.Portal.java (Portal.java:88)
Caused By: UnknownErrorException (YouFailed.java:99)
    at org.halp.no.error.SpamConsole.java (SpamConsole.java:254234)
    at org.dammit.internet.YouSuck.java (YouSuck.java:69)

**Comment by drtshock** [comment]
I'm going to chargeback my $1000000 donation I made to you

**Comment by np98765** [comment]
bump cuz this plugun sux and dosent wrk at all PLZ FIX KK?

**Comment by np98765** [comment]
bump cuz its been 15 secods adn noone ansered meeee

**Comment by turt2live** [comment]
omgeee this plugin has teh werst support evar

**Comment by davismariotti** [comment]
ikr ^

**Comment by SuperSpyTX** [comment]
dud lik i tired to run this on bungeecord serv and it duznt werk

mbax u no good codr i better and will writ bettr

**Comment by turt2live** [comment]
this plugin is lting my plyrs dupe diamnds!

hlllpp!! I cnt let them duppe diamonds!!

**Comment by SuperSpyTX** [comment]
@turt2live no no no!

i fix!

mbax y u lev a backdoor to nasa

**Comment by turt2live** [comment]
iok, i try to fix 2

**Comment by Iaccidentally** [comment]
how 2 plugin?

**Comment by mbax** [comment]
Fixed with the power of my brain

#6 #7

**Comment by lol768** [comment]
Yay :smile_cat:

**Comment by SuperSpyTX** [comment]
MBAX Y U LIER THE PLUGIN CRASHED MY SERVER.

**Comment by SuperSpyTX** [comment]
all gud i fixed it.
